REM [Header]
@ECHO OFF
                              
                                                  
                                                   
        

                                                       
                                                   
                      
                                      
                  

         
           
                                           
                  
       
                                  
                              

REM [CD-ROM Drive]      

REM C:\WINDOWS\COMMAND\MSCDEX.EXE /D:MSCD001       

REM [Display]   

REM MODE CON: COLS=80 LINES=25        

REM [Sound, MIDI, or Video Capture Card]        

REM SOUNDTST.COM

REM [Mouse]     

REM MOUSE.COM

REM [Miscellaneous]     


REM ******* DO NOT REMOVE *****
c:\dell\usbinfo.exe /addae   
REM ******* DO NOT REMOVE *****
