 ùAbstract: Natural Inclinations and Moral Absolutes: Not anUnmediated Correspondance for Aquinasú



	The classical text for explicating Aquinas's natural law (I™II, 94, 2) reads prima facie as if the goods of naturalinclinations and their contraries always correspond to a moralabsolute. This "Correspondance Interpretation" holds thatabsolute moral obligations somehow arise either directly fromnatural inclinations as inclinations or from their goods andcontraries. I argue that this cannot be the case and that therole natural inclinations play in establishing moral absolutes isa mediated one.